// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Description string `json:"description"`
	UserID      int    `json:"userId"`
}

type Todo struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
	Done        bool   `json:"done"`
	User        *User  `json:"user"`
}

type User struct {
	ID    int    `json:"id"`
	Login string `json:"login"`
}
