// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Description string `json:"description"`
	UserID      int    `json:"userId"`
}

type User struct {
	ID    int    `json:"id"`
	Login string `json:"login"`
}
